// Auto-generated version header
#ifndef SPARSEFLOW_VERSION_H
#define SPARSEFLOW_VERSION_H

#define SPARSEFLOW_VERSION_MAJOR 3
#define SPARSEFLOW_VERSION_MINOR 0
#define SPARSEFLOW_VERSION_PATCH 0
#define SPARSEFLOW_VERSION_STRING "3.0.0-alpha+738679a"

#endif // SPARSEFLOW_VERSION_H
